apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-devops-app
  template:
    metadata:
      labels:
        app: node-devops-app
    spec:
      containers:
        - name: node-app
          image: /node-devops-app
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
# how  to run your application
