apiVersion: v1
kind: Service
metadata:
  name: node-devops-service
spec:
  type: LoadBalancer
  selector:
    app: node-devops-app
  ports:
    - port: 80
      targetPort: 3000
  # how to access your application load balancing and networking and all
# changes
